---

- name: Create the Systemd Unit file for the bind-exporter service
  template:
    src: bind_exporter.systemd.j2
    dest: /etc/systemd/system/bind_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd and restart bind_exporter
  when: ansible_service_mgr == "systemd"

- name: Create the Upstart Unit file for the bind-exporter service
  template:
    src: bind_exporter.upstart.j2
    dest: /etc/init/bind_exporter.conf
    owner: root
    group: root
    mode: 0644
  notify: restart bind_exporter
  when: ansible_service_mgr == "upstart"

- name: Create the generic start-stop script for the bind-exporter service
  template:
    src: bind_exporter.service.j2
    dest: /etc/init.d/bind_exporter
    owner: root
    group: root
    mode: 0755
  notify: restart bind_exporter
  when: ansible_service_mgr not in [ "systemd", "upstart" ]
